#!/usr/bin/env python3
"""Generate placeholder intro-screen assets for an adventure.

An intro screen is a backdrop plus a labelled Play and Exit button that wiggle
under the pointer (see the Vania intro). The labels are words, so backdrop and
buttons are *localized* — one set per locale, with the locale's own text.

This emits, per locale, a flat-colour backdrop and a 3-frame button sheet per
button (frame 1 at rest, frames 2-3 tilted a degree either way, which reads as
a wiggle when cycled), packed as the usual vertical strip with a matching
.anim. It also emits the two click sounds: a short filtered noise blip each,
since a missing SFX is fatal at load time and the buttons need something to
play.

These are *placeholders to build the screen against*: real drawn buttons and
recorded clicks replace them file-for-file (same names, same .anim shape) via
the asset pipeline (ASSETS.md).

Usage:
  tools/gen_intro_placeholders.py --assets src/adventures/<adv>/assets \\
      --title "Gina la Gallina in Piscina"

Requires Pillow.
"""

import argparse
import math
import os
import struct
import wave

from PIL import Image, ImageDraw, ImageFont

SCREEN = (800, 600)
FRAMES = 3
TILT = 1.2  # degrees either side of rest — enough to read, small enough to sit still

# Labels per locale. A locale absent here can still be generated by passing
# --locale; it falls back to the English wording.
LABELS = {
    "it_IT": {"play": "GIOCA", "exit": "ESCI"},
    "en_US": {"play": "PLAY", "exit": "EXIT"},
}

# Button geometry matches the hotspots the scene declares.
BUTTONS = {
    "play_button": {"size": (280, 120), "fill": (76, 175, 110), "key": "play"},
    "exit_button": {"size": (265, 96), "fill": (192, 84, 76), "key": "exit"},
}

BACKDROP_TOP = (250, 233, 196)  # warm sand, so the hen reads against it
BACKDROP_BOTTOM = (176, 216, 232)  # pool blue
INK = (44, 52, 62)

FONT_PATH = "assets/fonts/AtkinsonHyperlegible-Regular.ttf"


def repo_root():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_font(size):
    path = os.path.join(repo_root(), FONT_PATH)
    if os.path.isfile(path):
        return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def centred_text(draw, box, text, font, fill):
    left, top, right, bottom = draw.textbbox((0, 0), text, font=font)
    x = box[0] + (box[2] - (right - left)) // 2 - left
    y = box[1] + (box[3] - (bottom - top)) // 2 - top
    draw.text((x, y), text, font=font, fill=fill)


def backdrop(title):
    image = Image.new("RGBA", SCREEN, BACKDROP_TOP + (255,))
    draw = ImageDraw.Draw(image)
    # A vertical wash, so the placeholder is obviously a backdrop and not a
    # missing-asset flat fill.
    for y in range(SCREEN[1]):
        t = y / (SCREEN[1] - 1)
        draw.line(
            [(0, y), (SCREEN[0], y)],
            fill=tuple(
                round(a + (b - a) * t)
                for a, b in zip(BACKDROP_TOP, BACKDROP_BOTTOM)
            ) + (255,),
        )
    centred_text(draw, (0, 60, SCREEN[0], 90), title, load_font(40), INK)
    return image


def button_frame(spec, label, angle):
    w, h = spec["size"]
    # Drawn on a padded canvas so the rotation has room, then cropped back: the
    # frame keeps its declared size whatever the tilt.
    pad = 24
    canvas = Image.new("RGBA", (w + pad * 2, h + pad * 2), (0, 0, 0, 0))
    draw = ImageDraw.Draw(canvas)
    draw.rounded_rectangle(
        [pad, pad, pad + w, pad + h], radius=h // 4,
        fill=spec["fill"] + (255,), outline=INK + (255,), width=4)
    centred_text(draw, (pad, pad, w, h), label, load_font(h // 3), (255, 255, 255))
    if angle:
        canvas = canvas.rotate(angle, resample=Image.BICUBIC, center=(pad + w / 2,
                                                                     pad + h / 2))
    return canvas.crop((pad, pad, pad + w, pad + h))


def write_sheet(base, frames):
    w, h = frames[0].size
    sheet = Image.new("RGBA", (w, h * len(frames)), (0, 0, 0, 0))
    for i, frame in enumerate(frames):
        sheet.paste(frame, (0, i * h))
    sheet.save(base + ".png")
    with open(base + ".anim", "w") as f:
        for i in range(len(frames)):
            f.write(f"0,{i * h},{w},{h}\n")
    print(f"  {base}.png ({w}x{h * len(frames)}) + .anim ({len(frames)} frames)")


def click_wav(path, freq, length=0.09):
    """A short percussive blip: a decaying sine, soft attack so it doesn't pop."""
    rate = 22050
    samples = []
    for n in range(int(rate * length)):
        t = n / rate
        attack = min(t / 0.004, 1.0)
        value = 0.35 * attack * math.exp(-28.0 * t) * math.sin(2 * math.pi * freq * t)
        samples.append(int(max(-1.0, min(1.0, value)) * 32767))
    with wave.open(path, "w") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(b"".join(struct.pack("<h", s) for s in samples))
    print(f"  {path} ({length * 1000:.0f}ms)")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--assets", required=True,
                        help="the adventure's assets dir (holds common/ and the locales)")
    parser.add_argument("--title", required=True, help="title drawn on the backdrop")
    parser.add_argument("--dir", default="intro", help="asset subdir (default intro)")
    parser.add_argument("--locale", action="append", dest="locales",
                        help="locale to emit (repeatable; default it_IT and en_US)")
    args = parser.parse_args()

    locales = args.locales or ["it_IT", "en_US"]
    for locale in locales:
        out = os.path.join(args.assets, locale, args.dir)
        os.makedirs(out, exist_ok=True)
        print(f"{locale}:")
        backdrop(args.title).save(os.path.join(out, "intro_background.png"))
        print(f"  {out}/intro_background.png ({SCREEN[0]}x{SCREEN[1]})")
        labels = LABELS.get(locale, LABELS["en_US"])
        for name, spec in BUTTONS.items():
            label = labels[spec["key"]]
            angles = [0.0, TILT, -TILT][:FRAMES]
            frames = [button_frame(spec, label, a) for a in angles]
            write_sheet(os.path.join(out, name), frames)

    # The clicks carry no words, so they live in the shared layer.
    common = os.path.join(args.assets, "common", args.dir)
    os.makedirs(common, exist_ok=True)
    print("common:")
    click_wav(os.path.join(common, "play_button_click.wav"), 880.0)
    click_wav(os.path.join(common, "exit_button_click.wav"), 523.25)


if __name__ == "__main__":
    main()
